// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarxaEFX3gIz81tsNNNZS0m9ct9IejCDA',
    appId: '1:195991091953:web:61c6d2329ac97ce2244750',
    messagingSenderId: '195991091953',
    projectId: 'atelier4-taha-elasri-iir5g7',
    authDomain: 'atelier4-taha-elasri-iir5g7.firebaseapp.com',
    storageBucket: 'atelier4-taha-elasri-iir5g7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBheZkZXSkR8X_hVOToO86Ry1MPQodPMzI',
    appId: '1:195991091953:android:136e2aac3f64f929244750',
    messagingSenderId: '195991091953',
    projectId: 'atelier4-taha-elasri-iir5g7',
    storageBucket: 'atelier4-taha-elasri-iir5g7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA-LY4qPifZfJLUju4F-5s9NSYrij5Lko',
    appId: '1:195991091953:ios:a825151e256b38f0244750',
    messagingSenderId: '195991091953',
    projectId: 'atelier4-taha-elasri-iir5g7',
    storageBucket: 'atelier4-taha-elasri-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4MohamedtahaElasriIir5g7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA-LY4qPifZfJLUju4F-5s9NSYrij5Lko',
    appId: '1:195991091953:ios:2856b0e375585697244750',
    messagingSenderId: '195991091953',
    projectId: 'atelier4-taha-elasri-iir5g7',
    storageBucket: 'atelier4-taha-elasri-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4MohamedtahaElasriIir5g7.RunnerTests',
  );
}
